## Reference 
## https://linuxhint.com/docker_volumes_docker_compose/
## https://docs.docker.com/compose/compose-file/#volumes

version: "3"

services:
    ordering:
        build:
            context: ./OrderingService
            args:
                buildno: 1
        volumes:
            - ./logs.json
            - ./orders.json
        ports:
            - "8080:80"

    monitoring:
        build:
            context: ./MonitoringService
            args:
                buildno: 1
        volumes:
            - ./logs.json
            - ./orders.json
        ports:
            - "81:81"

volumes:
    logsVolume:
    ordersVolume:
