## Reference 
## https://linuxhint.com/docker_volumes_docker_compose/
## https://docs.docker.com/compose/compose-file/#volumes

version: '3'

services:
    ordering:
        build:
            context: .
            dockerfile: ./OrderingService/Dockerfile
            args:
                buildno: 1
        volumes:
            - ./log.json:./log.json
            - ./orderType.json:./orderType.json
        ports:
            - "80:80"

    monitoring:
        build:
            context: .
            dockerfile: ./MonitoringService/Dockerfile
            args:
                buildno: 1
        volumes:
            - ./orderType.json:./orderType.json
            - ./log.json:./log.json
        ports:
            - "81:81"
    cache:
        image: "redis:latest"
